// <auto-generated />
namespace SocialNetWorkDBModel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class refactoring_db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(refactoring_db));
        
        string IMigrationMetadata.Id
        {
            get { return "201702141217539_refactoring_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
